### ISSUE TITLE
MDX extension activation error - cannot find module tslib

### ISSUE THREAD

**Issue by dlvhdr** [mdx-js/vscode-mdx#140]
### Extension not activating

Extension is not working in VS Code with the following error:

```
[2020-06-30 16:05:02.796] [exthost] [error] Activating extension JounQin.vscode-mdx failed due to an error:
[2020-06-30 16:05:02.798] [exthost] [error] Error: Cannot find module 'tslib'
Require stack:
- /Users/dolevh/.vscode/extensions/jounqin.vscode-mdx-0.1.4/client/lib/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:974:268)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:943:114)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:939:443)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/dolevh/.vscode/extensions/jounqin.vscode-mdx-0.1.4/client/lib/extension.js:7:17)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:974:268)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:943:114)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:939:443)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:33:115)
	at h._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:944:266)
	at h._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:838:856)
	at h._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:837:937)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:835:883)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:859)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:537
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:525)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:607:14)
	at h._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:836:618)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:846:159
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

### Your environment

*   **OS**: Mac OS Catalina

*   **Env**: yarn

### Steps to reproduce

Launch VS Code

### Expected behaviour

The extension should work and show eslint errors on mdx files.

### Actual behaviour

eslint doesn't show any errors on mdx files.
When running eslint from cli, errors are shown correctly.

**Comment by wollardj** [comment]
I'll share some additional env info since it's also happening on my machine:

```
> code --version
1.47.0
d5e9aa0227e057a60c82568bf31c04730dc15dcd
x64

> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

> yarn why tslib
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "tslib"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "tslib@1.11.0"
info Has been hoisted to "tslib"
info Reasons this module exists
   - Hoisted from "@typescript-eslint#typescript-estree#tsutils#tslib"
   - Hoisted from "webpack#chrome-trace-event#tslib"
   - Hoisted from "@storybook#components#react-focus-lock#use-sidecar#tslib"
   - Hoisted from "@storybook#react#react-dev-utils#inquirer#rxjs#tslib"
   - Hoisted from "@storybook#react#@storybook#core#html-webpack-plugin#html-minifier-terser#camel-case#tslib"
   - Hoisted from "@storybook#react#@storybook#core#html-webpack-plugin#html-minifier-terser#param-case#tslib"
   - Hoisted from "@storybook#react#@storybook#core#html-webpack-plugin#html-minifier-terser#param-case#dot-case#tslib"
   - Hoisted from "@storybook#react#@storybook#core#html-webpack-plugin#html-minifier-terser#camel-case#pascal-case#tslib"
   - Hoisted from "@storybook#react#@storybook#core#html-webpack-plugin#html-minifier-terser#param-case#dot-case#no-case#tslib"
   - Hoisted from "@storybook#react#@storybook#core#html-webpack-plugin#html-minifier-terser#param-case#dot-case#no-case#lower-case#tslib"
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "76KB"
info Disk size with transitive dependencies: "76KB"
info Number of shared dependencies: 0
=> Found "eslint-plugin-mdx#tslib@1.13.0"
info This module exists because "eslint-plugin-mdx" depends on it.
info Disk size without dependencies: "56KB"
info Disk size with unique dependencies: "56KB"
info Disk size with transitive dependencies: "56KB"
info Number of shared dependencies: 0
=> Found "eslint-mdx#tslib@1.13.0"
info This module exists because "eslint-plugin-mdx#eslint-mdx" depends on it.
info Disk size without dependencies: "56KB"
info Disk size with unique dependencies: "56KB"
info Disk size with transitive dependencies: "56KB"
info Number of shared dependencies: 0
```
